### ISSUE TITLE
Cant uninstall

### ISSUE THREAD

**Issue by maybepallab8** [John889/fapsecure-macos#2]

**Comment by John889** [comment]
Hey,
I'm really sorry that happened. Actually I've made an update to fix this issue. You can try downloading the last fapsecure zip file and running the latest fapsecure. Then try uninstalling. It should work. 
If it doesn't work, just let me know

**Comment by maybepallab08** [comment]
Hi, sorry to say, but i cant delete them with the latest zip. ive tried it thrice now with the timer. I am on macos ventura on m1 mac. thanks

**Comment by maybepallab08** [comment]
Please give me a way to remove the folder in shared folder if there is any.

**Comment by maybepallab08** [comment]
Formatting my mac seems to be the only way now

**Comment by John889** [comment]
No, wait.
I will send a code to remove it. When I get back home I'll send you sth

**Comment by John889** [comment]
Hey mate,

Sorry for being late. I have already tried replicating the issue you're getting many times, but I failed to do so. The problem seems to happen only on macOS Ventura and I can't test the app on Ventura at the moment. I believe I found the source of the problem. 
On Ventura, you need to enable Full disk access for Terminal in System Preferences, or you won't be able to execute many commands.
Go to Privacy & Security -> Full Disk Access and enable Terminal.
![image](https://github.com/John889/fapsecure-macos/assets/8354516/62bf05ba-da81-437c-a3d6-a0c17ca8bd23)

**Comment by John889** [comment]
Man, I'm really sorry for the trouble you had. But believe me I tried tons of times to replicate the issue and I released 2 updates for fapsecure thinking that it should fix the problem by cleaning the code, changing the execution directories, so it would work without any problem. This is the major change that could affect the code execution for fapsecure on Ventura. Please let me know if it doesn't work by any means. I still have solutions that will work for sure. Sorry for the trouble again.

**Comment by maybepallab08** [comment]
Hey, thanks for your response mate. Really appreciate your concern. 

I enabled Full Disk Access for Terminal and tried again. But, I still cant uninstall it. When I type the password, and hit Enter nothing shows up and the program exits. When I set the timer, the timer restarts again after 4 hours. I'd be glad just to uninstall the program for now. If there is any other way, please let me know. 

And, i believe there is an easy bypass for file protection in the program. I dont know if it exists only on Ventura. When I paste a new file with a same filename in the location of the protected file, the previous file gets replaced with a new one.

**Comment by John889** [comment]
hey mate,
so this script is what the uninstaller launches after a correct password is entered or after time's up when using the countdown method. I haven't made any changes to it. if it doesn't work I will just update the code that I think is causing the problem on Ventura and send another version. The problem could be in the timer itself, if that's the case then this script should work. Just do a chmod +x before executing it.

https://file.io/XyzLJHoPgrGV

**Comment by John889** [comment]
The link above can be used only once.

mate, and regarding the bypass of protected files, I don't think much could be about it. There are stronger protection methods, but some apps don't work will them. The only way could be by protecting the folder enclosing the file. I can still do some testing though. But the current protection method is the one that caused almost no problems with apps.

**Comment by maybepallab08** [comment]
hey mate, 
I still couldnt uninstall it. No effect of running the script at all.

**Comment by maybepallab08** [comment]
hi, it actually did work.
I copy pasted the script without chmod +x and it worked. Fapsecure seems to have been uninstalled from the system but there are files in my desktop and other location, which I still cannot delete because fapsecure has locked it. I actually tried to replace the original locked file during a fapsecure block . While doing that, I had to paste the locked file in a new location( desktop) . Now, i cant get rid of it. Let me know if there is anything that can be done.
Thanks.

**Comment by John889** [comment]
Hey,
Sorry for the late reply. Glad you finally got it to work
An easy way to unprotect those folders is to protect them using fapsecure then remove fapsecure again. Maybe you might want to change the timer delay to 1 or try removing using the password. I know you had enough of this, but this will really help me find where the problem is, so I can fix it for other people. I also wanted to tell you that I'm also using the same version of fapsecure to help me focus and block unwanted new apps on my mac. Even though I have the script to remove it, I block Terminal periodically(using other apps) to lock my settings.

**Comment by maybepallab08** [comment]
Hi, The script got removed on its own when fapsecure uninstalled. If you could provide the uninstallation script again, i can test it. I actually managed to delete those files by pasting a file with the same filename which replaced the original file and surprisingly i could delete the new file without any problem. Let me know if I can help in anyway.

**Comment by John889** [comment]
Hey mate, 

Thanks a lot, I don't want to cause any trouble. I think I might be able to test it on Ventura sometime soon. I could send you a copy of the removal script if you still can't unprotect certain files or folder. Thanks
